substitutions:
  deviceName: modecontrollertest
  mqttBroker: 10.0.1.108
  mqttUser:  switch

external_components:
- source:
    type: local
    path: esphome/components

esphome:
  name: ${deviceName}
  platform: ESP8266
  board: d1_mini
  build_path: devices/${deviceName}
  includes:
    - controller/

logger:


modecontroller:
  id: test
  base_class: esphome::modecontroller::BaseController
  controller:
   - esphome::modecontroller::ControllerA
   - esphome::modecontroller::ControllerB
  initial: esphome::modecontroller::ControllerB

output:
  - id: light_output
    platform: gpio
    pin: D6
light:
  - platform: binary
    output: light_output 
    id: led

binary_sensor:
    - platform: gpio
      pin:
        number: D5
        inverted: true
        mode: INPUT_PULLUP
      id: btnControl
      on_press: 
        then:
          - logger.log: "Hi!"
          - light.toggle: led
          - lambda: |-
              id(test).getActive()->btnPressed();