substitutions:
  deviceName: modecontrollertest
  mqttBroker: 10.0.1.108
  mqttUser:  switch

external_components:
- source:
    type: local
    path: esphome/components

esphome:
  name: ${deviceName}
  platform: ESP8266
  board: d1_mini
  build_path: devices/${deviceName}
  includes:
    - controller/

logger:


modecontroller:
  id: test
  controller:
   - esphome::modecontroller::ControllerA
   - esphome::modecontroller::ControllerB
  initial: esphome::modecontroller::ControllerB

binary_sensor:
    - platform: gpio
      pin:
        number: D3
        inverted: true
      id: btnControl
      on_click: 
        then:
          - lambda: |-
              //modecontroller::getActiveController<modecontroller::BaseController>(id(test))->